version: '3.7'
services:
    mongodb:
        image: mongo:latest
        ports:
            - {target: 27017, published: 27017, protocol: tcp}
    d2d-server:
        build:
            context: ./manor-d2d-api/
            dockerfile: Dockerfile
        ports:
            - {target: 5000, published: 5000, protocol: tcp}
        depends_on:
            - mongodb