export const GET_STREETS = 'GET_STREETS';
export const GET_STREETS_SUCCESS = 'GET_STREETS_SUCCESS';
export const GET_STREETS_ERROR = 'GET_STREETS_ERROR';
export const POPULATE_DB = 'POPULATE_DB';
export const POPULATE_DB_SUCCESS = 'POPULATE_DB_SUCCESS';
export const POPULATE_DB_ERROR = 'POPULATE_DB_ERROR';